(autoload 'ditz-init                            "ditz" "" t)
(autoload 'ditz-html                            "ditz" "" t)
(autoload 'ditz-add-release                     "ditz" "" t)
(autoload 'ditz-add                             "ditz" "" t)
(autoload 'ditz-status                          "ditz" "" t)
(autoload 'ditz-todo                            "ditz" "" t)
(autoload 'ditz-log                             "ditz" "" t)
(autoload 'ditz-show                            "ditz" "" t)
(autoload 'ditz-assign                          "ditz" "" t)
(autoload 'ditz-edit                            "ditz" "" t)
(autoload 'ditz-close                           "ditz" "" t)
(autoload 'ditz-drop                            "ditz" "" t)
(autoload 'ditz-release                         "ditz" "" t)
(autoload 'ditz-reload                          "ditz" "" t)
(autoload 'ditz-close-buffer                    "ditz" "" t)
(autoload 'ditz-mode                            "ditz" "" t)
(provide 'ditz-epackage-install)
