--- !ditz.rubyforge.org,2008-03-06/project 
name: emacs-ditz
version: "0.2"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: emacs-ditz
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :released
  release_time: 2008-04-10 20:33:03.982087 Z
  log_events: 
  - - 2008-04-10 20:26:45.696563 Z
    - Kentaro Kuribayashi <kentarok@gmail.com>
    - created
    - Initial release
  - - 2008-04-10 20:33:03.982121 Z
    - Kentaro Kuribayashi <kentarok@gmail.com>
    - released
    - Initial release
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.2"
  status: :released
  release_time: 2008-04-10 22:47:34.409110 Z
  log_events: 
  - - 2008-04-10 22:38:55.433199 Z
    - Kentaro Kuribayashi <kentarok@gmail.com>
    - created
    - ""
  - - 2008-04-10 22:47:34.409145 Z
    - Kentaro Kuribayashi <kentarok@gmail.com>
    - released
    - release 0.2
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.3"
  status: :released
  release_time: 2008-04-11 10:50:46.563357 Z
  log_events: 
  - - 2008-04-11 10:03:23.342376 Z
    - Kentaro Kuribayashi <kentarok@gmail.com>
    - created
    - ""
  - - 2008-04-11 10:50:46.563390 Z
    - Kentaro Kuribayashi <kentarok@gmail.com>
    - released
    - release 0.3
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.4"
  status: :released
  release_time: 2008-04-11 13:18:54.902624 Z
  log_events: 
  - - 2008-04-11 12:12:15.794477 Z
    - Kentaro Kuribayashi <kentarok@gmail.com>
    - created
    - ""
  - - 2008-04-11 13:18:54.902658 Z
    - Kentaro Kuribayashi <kentarok@gmail.com>
    - released
    - release 0.4
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.5"
  status: :released
  release_time: 2008-11-05 04:46:42.872290 Z
  log_events: 
  - - 2008-11-05 03:47:09.300501 Z
    - antipop <kentarok@gmail.com>
    - created
    - ""
  - - 2008-11-05 04:46:42.872306 Z
    - antipop <kentarok@gmail.com>
    - released
    - Released 0.5
